networks:
  internal:
    driver: bridge

services:
  og:
    container_name: 'Server'
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - internal
    ports:
      - 8080:8080
    environment:
      HEADLESS_SHELL: 1
  chrome:
    image: chromedp/headless-shell
    ports:
      - 9222:9222
    networks:
      - internal
